package com.example.bank.domain;

public enum AuditAction {
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGIN_BLOCKED,
    TOKEN_REFRESHED,
    REFRESH_TOKEN_REUSE_DETECTED,
    LOGOUT,
    ACCOUNT_OPENED,
    ACCOUNT_FROZEN,
    ACCOUNT_UNFROZEN,
    ACCOUNT_CLOSED,
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER,
    EXCHANGE,
    EXCHANGE_RATE_SET,
    PAYEE_ADDED,
    PAYEE_REMOVED
}
