-- V1: core banking schema.
-- Written in portable SQL that runs on PostgreSQL and on H2 in PostgreSQL mode.
-- Never edit this file once it has been applied anywhere; add V2, V3, ... instead.

-- "user" is a reserved word in PostgreSQL, so the table is "users".
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100)             NOT NULL,
    email         VARCHAR(255)             NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    role          VARCHAR(20)              NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(34)              NOT NULL,
    owner_id       BIGINT                   NOT NULL,
    currency       VARCHAR(3)               NOT NULL,
    status         VARCHAR(20)              NOT NULL,
    version        BIGINT                   NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_accounts_account_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_accounts_owner ON accounts (owner_id);

-- Money columns are NUMERIC(19,4): exact decimal arithmetic, never floating point.
CREATE TABLE transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(20)              NOT NULL,
    amount          NUMERIC(19, 4)           NOT NULL,
    currency        VARCHAR(3)               NOT NULL,
    status          VARCHAR(20)              NOT NULL,
    idempotency_key VARCHAR(100)             NOT NULL,
    description     VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_transactions_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_transactions_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')),
    CONSTRAINT ck_transactions_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0)
);

-- Double-entry bookkeeping: each transaction owns >= 2 entries whose DEBIT and CREDIT
-- totals are equal. An account's balance is computed from its entries; there is no
-- balance column to update, so there is nothing to get out of sync.
CREATE TABLE ledger_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT                   NOT NULL,
    account_id     BIGINT                   NOT NULL,
    direction      VARCHAR(10)              NOT NULL,
    amount         NUMERIC(19, 4)           NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ledger_entries_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_ledger_entries_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_ledger_entries_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_ledger_entries_amount_positive CHECK (amount > 0)
);

-- Balance queries (SUM per account) and statement/history queries (by account, by date).
CREATE INDEX idx_ledger_entries_account_created ON ledger_entries (account_id, created_at);
CREATE INDEX idx_ledger_entries_transaction ON ledger_entries (transaction_id);
