-- V4: audit trail of who did what, when, and from where.
-- Append-only, like the ledger. actor_user_id has no foreign key on purpose: an
-- audit row must stay exactly as written, whatever later happens to the user.
CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action        VARCHAR(50)              NOT NULL,
    outcome       VARCHAR(10)              NOT NULL,
    target_type   VARCHAR(30),
    target_id     VARCHAR(64),
    details       VARCHAR(1000),
    ip_address    VARCHAR(45),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_audit_logs_outcome CHECK (outcome IN ('SUCCESS', 'FAILURE'))
);

CREATE INDEX idx_audit_logs_created ON audit_logs (created_at);
CREATE INDEX idx_audit_logs_actor_created ON audit_logs (actor_user_id, created_at);
