-- V5: refresh tokens.
-- Only a SHA-256 hash of each token is stored, never the token itself (like
-- passwords): a leaked database dump can't be used to log in.
-- family_id groups one login session's chain of rotated tokens. If an
-- already-used token comes back, someone copied it, so the whole family is revoked.
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL,
    token_hash  VARCHAR(64)              NOT NULL,
    family_id   VARCHAR(36)              NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (family_id);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
