-- V6: currency exchange between a customer's own accounts (e.g. USD <-> KHR).
--
-- 1) FX accounts: the bank's position in each currency. Exchanging 10 USD to KHR
--    posts four entries, balanced per currency:
--      DEBIT customer USD 10      CREDIT FX-USD 10
--      DEBIT FX-KHR 40,900        CREDIT customer KHR 40,900
ALTER TABLE accounts DROP CONSTRAINT ck_accounts_type;
ALTER TABLE accounts ADD CONSTRAINT ck_accounts_type CHECK (type IN ('CUSTOMER', 'CASH', 'FX'));

-- 2) The EXCHANGE transaction type, and the second leg of an exchange: amount and
--    currency credited, plus the published rate used (quote units per 1 base unit).
ALTER TABLE transactions DROP CONSTRAINT ck_transactions_type;
ALTER TABLE transactions ADD CONSTRAINT ck_transactions_type
    CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'EXCHANGE'));
ALTER TABLE transactions ADD COLUMN counter_amount NUMERIC(19, 4);
ALTER TABLE transactions ADD COLUMN counter_currency VARCHAR(3);
ALTER TABLE transactions ADD COLUMN exchange_rate NUMERIC(19, 6);
ALTER TABLE transactions ADD COLUMN exchange_rate_base VARCHAR(3);

-- 3) Published rates, append-only: setting a new rate inserts a row, so the full
--    rate history is kept. The newest row per pair is the current rate.
--    buy_rate:  what the bank pays for 1 unit of the base currency (customer sells base)
--    sell_rate: what the bank charges for 1 unit of the base currency (customer buys base)
CREATE TABLE exchange_rates (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency  VARCHAR(3)               NOT NULL,
    quote_currency VARCHAR(3)               NOT NULL,
    buy_rate       NUMERIC(19, 6)           NOT NULL,
    sell_rate      NUMERIC(19, 6)           NOT NULL,
    created_by_id  BIGINT,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_exchange_rates_positive CHECK (buy_rate > 0 AND sell_rate >= buy_rate),
    CONSTRAINT ck_exchange_rates_pair CHECK (base_currency <> quote_currency)
);

CREATE INDEX idx_exchange_rates_pair ON exchange_rates (base_currency, quote_currency, id);
