-- V7: saved payees ("people I send money to").
-- The account number is stored rather than an account_id foreign key on purpose:
-- it is what the user typed and sees, and a payee may outlive the account.
CREATE TABLE payees (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id       BIGINT                   NOT NULL,
    nickname       VARCHAR(50)              NOT NULL,
    account_number VARCHAR(34)              NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_payees_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT uk_payees_owner_account UNIQUE (owner_id, account_number)
);
