-- V8: account security.

-- Email verification and two-step login (TOTP) state on the user.
-- totp_secret is stored encrypted (AES-GCM, key from configuration), never in clear.
-- totp_last_step remembers the last accepted 30-second window, so a code can't be reused.
ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN totp_secret VARCHAR(255);
ALTER TABLE users ADD COLUMN totp_enabled BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD COLUMN totp_last_step BIGINT;

-- Admins created before this version are trusted as verified.
UPDATE users SET email_verified_at = created_at WHERE role = 'ADMIN';

-- One-time 6-digit codes sent by email. Only a hash is stored; each code expires,
-- can be used once, and allows only a few wrong guesses.
CREATE TABLE user_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    purpose    VARCHAR(30)              NOT NULL,
    code_hash  VARCHAR(64)              NOT NULL,
    attempts   INTEGER DEFAULT 0        NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_codes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_user_codes_purpose CHECK (purpose IN ('VERIFY_EMAIL', 'RESET_PASSWORD'))
);

CREATE INDEX idx_user_codes_user_purpose ON user_codes (user_id, purpose, id);
